/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package akinatorGame;

import java.awt.Font;

/**
 *
 * @author alan
 */
public class akinator extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(akinator.class.getName());

    /**
     * Creates new form akinator
     */
    public akinator() {
        initComponents();
        lblResultado.setText("<html>Vou pensar em um valor de <strong>1</strong> a <strong>5</strong>. Tente adivinhar!</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spinNum = new javax.swing.JSpinner();
        btnChutar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spinNum.setFont(new java.awt.Font("Red Hat Mono", 0, 48)); // NOI18N
        spinNum.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spinNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 160, 60));

        btnChutar.setFont(new java.awt.Font("Red Hat Mono", 0, 36)); // NOI18N
        btnChutar.setText("Chutar");
        btnChutar.addActionListener(this::btnChutarActionPerformed);
        getContentPane().add(btnChutar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 170, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/akinator.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, -1, -1));

        lblResultado.setFont(new java.awt.Font("Red Hat Mono", 0, 24)); // NOI18N
        lblResultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblResultado.setText("Chute numero 1 a 5");
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 260, 160));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balao2.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, -60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChutarActionPerformed
        int num = Integer.parseInt(spinNum.getValue().toString());
        double ale = 1 + Math.random() *(6-1);
        int aleI = (int) ale;
        String res=(aleI==num)?"Acertou!":("Errou! Pensei em "+aleI);
        lblResultado.setFont(new Font("Arial Black", Font.BOLD, 24));
        lblResultado.setText(res);
    }//GEN-LAST:event_btnChutarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new akinator().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChutar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JSpinner spinNum;
    // End of variables declaration//GEN-END:variables
}
